//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime dob { get; set; }
        public string address { get; set; }
        public byte gender { get; set; }
        public System.DateTime startdate { get; set; }
        public int department_id { get; set; }
        public int salary_id { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Salary Salary { get; set; }
    }
}
